global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'telegram_receiver'

receivers:
- name: 'telegram_receiver'
  webhook_configs:
  - send_resolved: true
    url: 'https://api.telegram.org/bot6005683480:AAEQWHeUZNxdaK5wqu31gPzWDbEYw41BgOk/sendMessage?chat_id=887216174&text=CPU usage is above 50% for 1 minute'
