version: '3.3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor_net

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    ports:
      - '8428:8428'
    command: >
      -storageDataPath /victoria-metrics-data
      -promscrape.config=/etc/victoriametrics/promscrape.yml
      vmalert -rule=/etc/vm/rules/alert.rules.yml --datasource=http://localhost:8428 --notifier.url=http://alertmanager:9093
      -rule.path=/etc/vm/rules/*
    volumes:
      - ./promscrape.yml:/etc/victoriametrics/promscrape.yml
      - ./alert.rules.yml:/etc/vm/rules/alert.rules.yml
    networks:
      - monitor_net
    depends_on:
      - cadvizor
      - alertmanager

  cadvizor:
    image: google/cadvisor:latest
    container_name: cadvizor
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitor_net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitor_net

  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert
    depends_on:
      - victoriametrics
    command:
      - '--rule=/etc/vm/rules/alert.rules.yml'
      - '--datasource.url=http://victoriametrics:8428'
      - '--notifier.url=http://alertmanager:9093'
    volumes:
      - ./alert.rules.yml:/etc/vm/rules/alert.rules.yml
    networks:
      - monitor_net

volumes:
  grafana-storage:

networks:
  monitor_net:
    driver: bridge
